### ISSUE TITLE
Author Name and Update Time Not Appearing on Pages

### ISSUE THREAD

**Issue by Tacktician** [saucelabs/sauce-docs#58]
## 📃 Documentation Issue

`showLastUpdateAuthor` and `showLastUpdateTime` not appearing on any pages, therefore not abiding with SOC2 Compliance.

__Doc URL:__ NA

## Suggested Fix

Add the following step to GitHub Actions. The `checkout` action apparently only fetches the latest commit. See [Issue #2798](https://github.com/facebook/docusaurus/issues/2798) for details.

```yaml
steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
```

## Documentation Checklist

Indicate the type of doc fix by completing the checklist below.

- [ ] Typos
- [ ] Grammar
- [ ] Incorrect information
- [x] Missing information
